---
system_upgrade: true

packages_blocklist:
  - apport*
  - autofs
  - avahi*
  - avahi-*
  - beep
  - git
  - pastebinit
  - popularity-contest
  - prelink
  - rpcbind
  - rsh*
  - rsync
  - talk*
  - telnet*
  - tftp*
  - tuned
  - whoopsie
  - xinetd
  - yp-tools
  - ypbind

packages_debian:
  - acct
  - apparmor-profiles
  - apparmor-utils
  - auditd
  - cracklib-runtime
  - libpam-apparmor
  - libpam-cap
  - libpam-modules
  - libpam-pwquality
  - lsb-release
  - needrestart
  - openssh-server
  - postfix
  - rsyslog
  - sysstat

packages_ubuntu:
  - fwupd
  - secureboot-db
  - snapd
