---
faillock_enable: true
faillock_admin_group: []
faillock_audit: true
faillock_deny: 5
faillock_dir: /var/run/faillock
faillock_even_deny_root: true
faillock_fail_interval: 900
faillock_local_users_only: true
faillock_no_log_info: false
faillock_nodelay: true
faillock_root_unlock_time: 600
faillock_silent: false
faillock_unlock_time: 600
faillock_conf_template: "faillock.conf.j2"

login_defs_login_retries: 5
login_defs_login_timeout: 60
login_defs_pass_max_days: 60
login_defs_pass_min_days: 1
login_defs_pass_warn_age: 7

login_defs_template: "login.defs.j2"

password_remember: 5

common_password_template: "common-password.j2"
common_account_template: "common-account.j2"
common_auth_template: "common-auth.j2"
login_template: "login.j2"
pwquality_conf_template: "pwquality.conf.j2"

pwquality_dcredit: -1
pwquality_dictcheck: 1
pwquality_dictpath: ""
pwquality_difok: 8
pwquality_enforce_for_root: true
pwquality_enforcing: 1
pwquality_gecoscheck: 1
pwquality_lcredit: -1
pwquality_local_users_only: true
pwquality_maxclassrepeat: 4
pwquality_maxrepeat: 3
pwquality_minclass: 4
pwquality_minlen: 15
pwquality_ocredit: -1
pwquality_retry: 3
pwquality_ucredit: -1
pwquality_usercheck: 1
pwquality_usersubstr: 3
