---
- name: Remove users
  become: true
  ansible.builtin.user:
    name: "{{ item }}"
    state: absent
    remove: true
  register: remove_users
  loop:
    - "{{ delete_users }}"
  failed_when: >
    remove_users is not success and
    not ("not removing" in remove_users.msg or
    "not found" in remove_users.msg)
  tags:
    - users

- name: Stat user /home directories
  ansible.builtin.find:
    paths: /home
    file_type: directory
  register: home_directories
  tags:
    - users

- name: Set user /home directories permission
  become: true
  ansible.builtin.file:
    mode: "0750"
    path: "{{ item.path }}"
  loop: "{{ home_directories.files }}"
  loop_control:
    label: "{{ item.path }}"
  tags:
    - users
