---
- name: Some name
  hosts: all

  tasks:
    - name: log user
      block:
        - name: run whoami
          ansible.builtin.command: whoami
          register: whoami

        - name: log result
          ansible.builtin.debug:
            msg: "{{ whoami }}"

    - name: Include required roles
      ansible.builtin.include_role:
        name: "{{item}}"
      loop: "{{required_roles}}"

    - name: Include active roles
      ansible.builtin.include_role:
        name: "{{item}}"
      loop: "{{active_roles}}"

    - name: Say hello
      ansible.builtin.debug:
        msg: "{{ compilers }}"
