---
- name: Configure login.defs
  become: true
  ansible.builtin.template:
    src: "{{ login_defs_template }}"
    dest: /etc/login.defs
    backup: true
    mode: "0644"
    owner: root
    group: root
  tags:
    - login
