---
- name: Merge package lists
  ansible.builtin.set_fact:
    packages_merged: "{{ packages_debian + packages_ubuntu }}"
  tags:
    - packages

- name: Generic package removal
  become: true
  ansible.builtin.package:
    name: "{{ packages_blocklist }}"
    state: absent
  register: package_removal
  failed_when: package_removal is not success and not "No package" in package_removal.msg
  tags:
    - packages

- name: Configure needrestart
  tags:
    - needrestart
    - packages
  block:
    - name: Pre register needrestart configuration directory
      become: true
      ansible.builtin.stat:
        path: /etc/needrestart/conf.d
      register: needrestart_directory_created

    - name: Create needrestart directory
      become: true
      ansible.builtin.file:
        path: /etc/needrestart/conf.d
        state: directory
        owner: root
        group: root
        mode: "0755"
        recurse: true
      when: ("needrestart" in packages_merged) and not needrestart_directory_created.stat.exists

    - name: Stat needrestart configuration directory
      become: true
      ansible.builtin.stat:
        path: /etc/needrestart/conf.d
      register: needrestart_directory

    - name: Get needrestart restart value
      ansible.builtin.command:
        cmd: grep -Rqo "$nrconf{restart} = 'l';" /etc/needrestart/conf.d/
      register: needrestart_restart_set
      when: needrestart_directory.stat.exists
      changed_when: needrestart_restart_set.rc != 0
      failed_when: needrestart_restart_set.rc > 1

    - name: Configure needrestart
      become: true
      ansible.builtin.lineinfile:
        path: /etc/needrestart/conf.d/00-restart.conf
        line: $nrconf{restart} = 'l';
        create: true
        owner: root
        group: root
        mode: "0644"
      when: needrestart_directory.stat.exists and needrestart_restart_set.rc != 0

- name: Debian family package installation
  become: true
  ansible.builtin.apt:
    name: "{{ packages_merged }}"
    state: present
    install_recommends: false
  tags:
    - packages

- name: update-notifier-common-package installation
  become: true
  ansible.builtin.apt:
    name: update-notifier-common
    state: present
    install_recommends: false
  tags:
    - packages

- name: Run apt purge
  become: true
  ansible.builtin.apt:
    name: "{{ packages_blocklist }}"
    state: absent
    purge: true
  register: apt_purge
  failed_when: apt_purge is not success and not "No package" in apt_purge.msg
  tags:
    - packages

- name: Install rng-tools
  become: true
  ansible.builtin.package:
    name: rng-tools
    state: present
  when: ansible_local.cpuinfo.rdrand
  tags:
    - rng-tools
    - packages

- name: Stat sysstat default
  become: true
  ansible.builtin.stat:
    path: /etc/default/sysstat
  register: default_sysstat
  tags:
    - packages
    - sysstat

- name: Enable sysstat
  become: true
  ansible.builtin.lineinfile:
    regexp: ^ENABLED
    line: ENABLED="true"
    dest: /etc/default/sysstat
    mode: "0644"
    state: present
    create: false
    backrefs: true
  when: default_sysstat.stat.exists
  tags:
    - packages
    - sysstat

- name: Remove unneeded Debian dependencies
  become: true
  ansible.builtin.apt:
    autoclean: true
    autoremove: true
  when: ansible_os_family == "Debian"
  tags:
    - packages
