---
- name: Remove cron.deny and at.deny
  become: true
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - /etc/at.deny
    - /etc/cron.deny
  tags:
    - at
    - cron

- name: Clean cron and at
  become: true
  ansible.builtin.lineinfile:
    path: "{{ item }}"
    regexp: ^(?!root).*$
    state: absent
  loop:
    - /etc/at.allow
    - /etc/cron.allow
  tags:
    - at
    - cron

- name: Allow root cron and at
  become: true
  ansible.builtin.lineinfile:
    path: "{{ item }}"
    line: root
    mode: "0600"
    state: present
    create: true
  loop:
    - /etc/at.allow
    - /etc/cron.allow
  tags:
    - at
    - cron

- name: Mask atd
  become: true
  ansible.builtin.systemd:
    name: atd
    masked: true
    enabled: false
    state: stopped
  register: mask_atd
  failed_when: mask_atd is not success and not "Could not find the requested service" in mask_atd.msg
  tags:
    - at
    - systemd

- name: Set cron permissions
  become: true
  ansible.builtin.file:
    path: "{{ item }}"
    mode: "0700"
    owner: root
    group: root
  register: cron_perm
  failed_when: cron_perm is not success and not 'is absent, cannot continue' in cron_perm.msg
  loop:
    - /etc/cron.d
    - /etc/cron.daily
    - /etc/cron.hourly
    - /etc/cron.weekly
    - /etc/cron.monthly
  tags:
    - cron

- name: Set crontab permissions
  become: true
  ansible.builtin.file:
    path: /etc/crontab
    mode: "0600"
    owner: root
    group: root
  register: crontab_perm
  failed_when: crontab_perm is not success and not 'is absent, cannot continue' in crontab_perm.msg
  tags:
    - cron
    - crontab
