---
- name: Converge
  hosts: all

  tasks:
    - name: Update apt cache (on Debian).
      become: true
      apt:
        update_cache: true

    - name: Install ssh
      apt:
        name: ssh
        state: present

    - name: Handle previlage bug
      block:
        - name: change conf file
          ansible.builtin.lineinfile:
            path: /usr/lib/tmpfiles.d/sshd.conf
            line: "d /run/sshd 0755 root root"
            state: present
            create: true
            owner: root
            group: root
            mode: "0600"

        - name: restart ssh
          ansible.builtin.service:
            name: ssh
            state: restarted

- import_playbook: ../../main.yml
