---
- name: Set crypto-policies config as fact
  tags:
    - fact
    - crypto-policy
  block:
    - name: Stat crypto-policies config
      ansible.builtin.stat:
        path: /etc/crypto-policies/config
      register: stat_crypto_policies_config

    - name: Set config fact
      ansible.builtin.set_fact:
        crypto_policies_config: "{{ stat_crypto_policies_config.stat.exists }}"

- name: Set sysctl configuration directory as fact
  tags:
    - fact
    - sysctl
  block:
    - name: Stat /usr/lib/sysctl.d/ exists
      ansible.builtin.stat:
        path: /usr/lib/sysctl.d/
      register: usr_lib_sysctl_d

    - name: Set sysctl fact
      ansible.builtin.set_fact:
        sysctl_conf_dir: "{{ '/usr/lib/sysctl.d' if usr_lib_sysctl_d.stat.exists else '/etc/sysctl.d' }}"
