---
- name: Set crypto-policies config as fact
  tags:
    - fact
    - crypto-policy
  block:
    - name: Stat crypto-policies config
      ansible.builtin.stat:
        path: /etc/crypto-policies/config
      register: stat_crypto_policies_config

    - name: Set config fact
      ansible.builtin.set_fact:
        crypto_policies_config: "{{ stat_crypto_policies_config.stat.exists }}"
