---
- name: Update Debian cracklib
  become: true
  ansible.builtin.shell: |
    update-cracklib
  register: update_debian_cracklib
  changed_when: update_debian_cracklib.rc == 0
  when: ansible_os_family == "Debian"
