---
- name: Disable misc kernel modules
  become: true
  ansible.builtin.lineinfile:
    dest: /etc/modprobe.d/disablemod.conf
    line: install {{ item }} /bin/true
    mode: "0644"
    owner: root
    group: root
    state: present
    create: true
  with_items:
    - "{{ misc_modules_blocklist }}"
  tags:
    - modprobe

- name: Stat blacklisted kernel modules
  environment:
    PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
  ansible.builtin.shell: |
    set -o pipefail
    modprobe -c | grep -o '^blacklist .*' | awk '{print $2}'
  args:
    executable: /bin/bash
  changed_when: false
  failed_when: modprobe_blacklist.rc != 0
  register: modprobe_blacklist
  when: block_blacklisted | bool
  tags:
    - modprobe

- name: Block blacklisted kernel modules
  become: true
  ansible.builtin.lineinfile:
    dest: /etc/modprobe.d/blockblacklisted.conf
    line: install {{ item }} /bin/true
    mode: "0644"
    owner: root
    group: root
    state: present
    create: true
  with_items:
    - "{{ modprobe_blacklist.stdout_lines | sort }}"
  when: block_blacklisted | bool
  tags:
    - modprobe
